CBIB/Models/Journal.cs
using System.ComponentModel.DataAnnotations;

namespace CBIB.Models
{
    public class Journal
    {
        public long ID { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Research Output")]
        public string Type { get; set; }

        [Display(Name = "Author 1")]
        public string CoAuthor1 { get; set; }

        [Display(Name = "Author 2")]
        public string CoAuthor2 { get; set; }

        [Required]
        public string Year { get; set; }

        [Required]
        public string Abstract { get; set; }

        [Display(Name = "Proof of Peer Review")]
        public string ProofOfpeerReview { get; set; }

        [Display(Name = "Peer Reviewed?")]

        public bool PeerReviewed { get; set; }

        public string url { get; set; }

        public string PeerUrl { get; set; }

        public long AuthorID { get; set; }

        public Author Author { get; set; }
    }
}

CBIB/Controllers/JournalsController.cs
using CBIB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CBIB.Controllers
{
    public class JournalsController : Controller
    {
        private readonly CBIBContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        private IHostingEnvironment _environment;

        public JournalsController(CBIBContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment environment)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
        }

        // GET: Journals
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Global Administrator"))
            {
                return View(await _context.Journal.ToListAsync());
            }
            var user = await _userManager.GetUserAsync(User);
            var currentAuthor = _context.Author.Find(user.AuthorID);

            var journalsList = await _context.Journal.Where(a => a.AuthorID.Equals(currentAuthor.AuthorID)).ToListAsync();

            var CoAuthorList = await _context.Journal.Where(a => a.CoAuthor1.Equals(currentAuthor.Name)).ToListAsync();

            foreach (Journal coAuthor in CoAuthorList)
            {
                journalsList.Add(coAuthor);
            }

            CoAuthorList = await _context.Journal.Where(a => a.CoAuthor2.Equals(currentAuthor.Name)).ToListAsync();

            foreach (Journal coAuthor in CoAuthorList)
            {
                journalsList.Add(coAuthor);
            }
            return View(journalsList);
        }

        // GET: Journals/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journal
                .SingleOrDefaultAsync(m => m.ID == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        // GET: Journals/Create
        [HttpGet]
        public IActionResult Create()
        {
            List<string> journalTypes = new List<String>();

            journalTypes.Insert(0,"Select");
            journalTypes.Insert(1, "Conference Paper");
            journalTypes.Insert(2, "Journal");
            journalTypes.Insert(3, "Thesis");
            journalTypes.Insert(4, "Workshop Paper");
            journalTypes.Insert(5, "Book");
            journalTypes.Insert(6, "Book Chapter");
            journalTypes.Insert(7, "Technical Report");

            ViewBag.ListOfJournals = journalTypes.OrderBy(j=>j);

            List<Author> coAuthors = new List<Author>();

            coAuthors = (from Name in _context.Author select Name).OrderBy(n=>n.Name).ToList();

            coAuthors.Insert(0, new Author
            {
                AuthorID = 0,
                Name = "Select"
            });

            ViewBag.ListOfNodes = coAuthors;

            return View();
        }

        //Task Download
        public async Task<IActionResult> JournalDownload(long id)
        {
            return File((await Download(id, "JournalUrl")), "application/pdf", "Too.pdf");
        }

        [Authorize(Roles = "Global Administrator, Node Administrator")]
        public async Task<IActionResult> PeerReviewDownload(long id)
        {
            return File((await Download(id, "PeerUrl")), "application/pdf", "Too.pdf");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Type,Year,Abstract")] Journal journal, IFormFile file1, IFormFile file2, Journal listBox)
        {
            var user = await _userManager.GetUserAsync(User);
            var author = _context.Author.Find(user.AuthorID);

            if (ModelState.IsValid)
            {
                if (!listBox.CoAuthor1.Equals("0"))
                {
                    journal.CoAuthor1 = await FindAuthorName(listBox.CoAuthor1);
                }

                if (!listBox.CoAuthor2.Equals("0"))
                {
                    journal.CoAuthor2 = await FindAuthorName(listBox.CoAuthor2);
                }

                if (listBox.Type.Equals("0"))
                {
                    journal.Type = await FindAuthorName(listBox.Type);
                }

                journal.AuthorID = user.AuthorID;

                if (file1 != null)
                {
                    journal.url = await Upload(file1);
                }

                if (file2 != null)
                {
                    journal.PeerUrl = await Upload(file2);
                }

                journal.ProofOfpeerReview = "This journal has not yet been peer reviewed";

                journal.Author = author;

                _context.Add(journal);
                await _context.SaveChangesAsync();

                author.Journals.Add(journal);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(journal);
        }

        // GET: Journals/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journal.SingleOrDefaultAsync(m => m.ID == id);

            List<Author> coAuthors = new List<Author>();

            coAuthors = (from Name in _context.Author select Name).ToList();

            coAuthors.Insert(0, new Author
            {
                AuthorID = 0,
                Name = "Select"
            });

            ViewBag.ListOfNodes = coAuthors;

            if (journal == null)
            {
                return NotFound();
            }
            return View(journal);
        }

        // POST: Journals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ID,Title,Type,Year,Abstract,PeerReviewed")] Journal journal, IFormFile file1, IFormFile file2, Journal listBox)
        {
            if (id != journal.ID)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            var author = _context.Author.Find(user.AuthorID);
            var currentJournal = _context.Journal.Find(id);
            _context.Entry(currentJournal).State = EntityState.Detached;

            if (ModelState.IsValid)
            {
                try
                {
                    if (!listBox.CoAuthor1.Equals("0"))
                    {
                        journal.CoAuthor1 = await FindAuthorName(listBox.CoAuthor1);
                    }
                    else
                    {
                        journal.CoAuthor1 = currentJournal.CoAuthor1;
                    }

                    if (!listBox.CoAuthor2.Equals("0"))
                    {
                        journal.CoAuthor2 = await FindAuthorName(listBox.CoAuthor2);
                    }
                    else
                    {
                        journal.CoAuthor2 = currentJournal.CoAuthor2;
                    }

                    journal.AuthorID = user.AuthorID;

                    if (file1 != null)
                    {
                        journal.url = await Upload(file1);
                    }

                    if (file2 != null)
                    {
                        journal.PeerUrl = await Upload(file2);
                    }

                    if(journal.PeerReviewed)
                    {
                        journal.ProofOfpeerReview = "This journal has been peer reviewed";
                    }
                    else
                    {
                        journal.ProofOfpeerReview = currentJournal.ProofOfpeerReview;
                    }

                    _context.Update(journal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JournalExists(journal.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(journal);
        }

        private Task<string> FindAuthorName(Task<string> task)
        {
            throw new NotImplementedException();
        }

        // GET: Journals/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journal
                .SingleOrDefaultAsync(m => m.ID == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        // POST: Journals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var journal = await _context.Journal.SingleOrDefaultAsync(m => m.ID == id);
            _context.Journal.Remove(journal);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool JournalExists(long id)

CBIB/Views/Journals/Create.cshtml
@model CBIB.Models.Journal

@{
    ViewData["Title"] = "Create";
}



<div class="container body-content">
    <h2>Create</h2>
    <form method="post" enctype="multipart/form-data" asp-controller="Journals" asp-action="Create">
        <div class="container body-content">
        </div>
        <div class="form-horizontal">
            <h4>Journal</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <label asp-for="Type" class="col-lg-1 col-lg-offset-1"></label>
                <div class="col-md-10">
                    <select asp-for="Type" class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListOfJournals,"Type"))"></select>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        @if (ViewBag.SelectedValue != null)
                        {
                            <text>Selected Country ID: </text> @ViewBag.SelectedValue;
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <label asp-for="CoAuthor1" class="col-lg-1 col-lg-offset-1"></label>
                <div class="col-md-10">
                    <select asp-for="CoAuthor1" class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListOfNodes,"AuthorID", "Name"))"></select>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        @if (ViewBag.SelectedValue != null)
                        {
                            <text>Selected Country ID: </text> @ViewBag.SelectedValue;
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <label asp-for="CoAuthor2" class="col-sm-1 col-lg-offset-1"></label>
                <div class="col-md-10">
                    <select asp-for="CoAuthor2" class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListOfNodes,"AuthorID", "Name"))"></select>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        @if (ViewBag.SelectedValue != null)
                        {
                            <text>Selected Country ID: </text> @ViewBag.SelectedValue;
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Year" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Year" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Abstract" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea asp-for="Abstract" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Abstract" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10 col-lg-offset-2">
                    <p>Upload pdf related to publication:</p>
                    <input type="file" name="file1" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10 col-lg-offset-2">
                    <p>Upload pdf proof of peer review</p>
                    <input type="file" name="file2" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

    </form>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CBIB/Views/Journals/Delete.cshtml
@model CBIB.Models.Journal

@{
    ViewData["Title"] = "Delete";
}
<div class="container body-content">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Journal</h4>
        <hr />
        <dl class="dl-horizontal">
            <input type="hidden" asp-for="ID" />
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Year)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Year)
            </dd>
        </dl>

        <form asp-action="Delete">
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div> 

CBIB/Views/Journals/Details.cshtml
@model CBIB.Models.Journal
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Details";
}
<div class="container body-content">
    <h2>Details</h2>

    <div>
        <h4>Journal</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Type)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Type)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CoAuthor1)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CoAuthor1)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CoAuthor2)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CoAuthor2)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Year)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Year)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Abstract)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Abstract)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProofOfpeerReview)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ProofOfpeerReview)
            </dd>
        </dl>
    </div>

    <div>
        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> ||
        <a asp-action="Index">Back to List</a> ||
        <a asp-controller="Journals" asp-action="JournalDownload" asp-route-id="@Model.ID">Download pdf copy of Journal</a> ||
        @if (User.IsInRole("Global Administrator") || User.IsInRole("Node Administrator"))
        {
            <a asp-controller="Journals" asp-action="PeerReviewDownload" asp-route-id="@Model.ID">Download pdf copy of Peer Review</a>
        }
    </div>

</div>

CBIB/Views/Journals/Edit.cshtml
@model CBIB.Models.Journal

@{
    ViewData["Title"] = "Edit";
}
<div class="container body-content">
    <h2>Edit</h2>

    <form asp-action="Edit">
        <div class="form-horizontal">
            <h4>Journal</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Title" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Type" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Type" class="form-control" />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <label asp-for="CoAuthor1" class="col-lg-1 col-lg-offset-1"></label>
                <div class="col-md-10">
                    <select asp-for="CoAuthor1" class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListOfNodes,"AuthorID", "Name"))"></select>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        @if (ViewBag.SelectedValue != null)
                        {
                            <text>Selected Country ID: </text> @ViewBag.SelectedValue;
                        }
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <label asp-for="CoAuthor2" class="col-sm-1 col-lg-offset-1"></label>
                <div class="col-md-10">
                    <select asp-for="CoAuthor2" class="form-control"
                            asp-items="@(new SelectList(@ViewBag.ListOfNodes,"AuthorID", "Name"))"></select>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        @if (ViewBag.SelectedValue != null)
                        {
                            <text>Selected Country ID: </text> @ViewBag.SelectedValue;
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Year" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Year" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Abstract" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea asp-for="Abstract" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="Abstract" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10 col-lg-offset-2">
                    <p>Update pdf related to publication:</p>
                    <input type="file" name="file1" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10 col-lg-offset-2">
                    <p>Update pdf proof of peer review</p>
                    <input type="file" name="file2" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="checkbox">
                        <label asp-for="PeerReviewed">
                            <input asp-for="PeerReviewed" />
                            @Html.DisplayNameFor(m => m.PeerReviewed)
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>

    </form>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CBIB/Views/Journals/Index.cshtml
@model IEnumerable<CBIB.Models.Journal>

@{
    ViewData["Title"] = "Index";
}
<div class="container body-content">
    <h3>List of my Journals</h3>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Year)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Year)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>