CBIB/Models/Author.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CBIB.Models
{
    public class Author
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long AuthorID { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }

        public ICollection<Journal> Journals { get; set; }
        public long NodeID { get; set; }
        //public Node AuthorNode { get; set; }
    }
}

CBIB/Controllers/AuthorsController.cs
using CBIB.Models;
using CBIB.Views.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CBIB.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly CBIBContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public AuthorsController(CBIBContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Authors
        public async Task<IActionResult> Index(string id)
        {
            //    var movies = from m in _context.Author select m;

            //if (!String.IsNullOrEmpty(id))
            //{
            //    movies = movies.Where(s => s.Name.Contains(id));
            //}
            //return View(await movies.ToListAsync());

            AuthorIndexViewModel avm = new AuthorIndexViewModel();
            List<Author> AuthorList = null;
            List<Node> NodesList = null;

            var user = await _userManager.GetUserAsync(User);
            Author currentAuthor = await _context.Author.FindAsync(user.AuthorID);

            if (User.IsInRole("Global Administrator"))
            {
                AuthorList = await _context.Author.ToListAsync();
                NodesList = await _context.Node.ToListAsync();
                avm.dict = Display(AuthorList, NodesList);
            }

            else if (User.IsInRole("Node Administrator"))
            {
                AuthorList = await _context.Author.Where(s => s.NodeID.Equals(currentAuthor.NodeID)).ToListAsync();
                NodesList = NodesList = await _context.Node.Where(s => s.ID.Equals(currentAuthor.NodeID)).ToListAsync();
                avm.dict = Display(AuthorList, NodesList);
            }
            else
            {
                var Authors = _context.Author.Where(s => s.NodeID.Equals(currentAuthor.NodeID));

                AuthorList = await Authors.ToListAsync();
            }

            return View(avm);

        }

        // GET: Authors/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .Include(j => j.Journals)
                .AsNoTracking()
                .SingleOrDefaultAsync(m => m.AuthorID == id);

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuthorID,Firstname,Lastname")] Author author)
        {
            if (ModelState.IsValid)
            {
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author.SingleOrDefaultAsync(m => m.AuthorID == id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("AuthorID,Firstname,Lastname")] Author author)
        {
            if (id != author.AuthorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.AuthorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _context.Author
                .SingleOrDefaultAsync(m => m.AuthorID == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var author = await _context.Author.SingleOrDefaultAsync(m => m.AuthorID == id);
            _context.Author.Remove(author);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool AuthorExists(long id)
        {
            return _context.Author.Any(e => e.AuthorID == id);
        }

        private IDictionary<Author, string> Display(List<Author> authorList, List<Node> nodeList)
        {
            IDictionary<Author, string> dictionary = new Dictionary<Author, string>();

            foreach (Author author in authorList)
            {
                foreach (Node node in nodeList)
                {
                    if (author.NodeID.Equals(node.ID))
                    {
                        dictionary.Add(author, node.Name);
                    }
                }
            }
            return dictionary;
        }
    }
}

CBIB/Views/Authors/Details.cshtml
@model CBIB.Models.Author

@{
    ViewData["Title"] = "Details";
}
<div class="container body-content">
    <h3>List of research papers </h3>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Journals<br />
            </dt>
            <dd>
                <table class="table">
                    <tr>
                        <th>Title</th>
                        <th>Year</th>
                    </tr>
                    @foreach (var item in Model.Journals)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Year)
                            </td>
                        </tr>
                    }
                </table>
            </dd>

        </dl>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</div>

CBIB/Views/Authors/Edit.cshtml
@model CBIB.Models.Author

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="AuthorID" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CBIB/Views/Authors/Index.cshtml
@*@model IEnumerable<CBIB.Models.Author>*@

@model CBIB.Views.ViewModels.AuthorIndexViewModel
@{
    ViewData["Title"] = "Index";
}
<div class="container body-content">
    <h3>Authors</h3>

    <form asp-controller="Authors" asp-action="Index">
        <p>
            <input type="text" name="id">
            <input type="submit" value="search" />
        </p>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Author Name</th>
                <th>Node</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.dict)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Key.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Value)
                    </td>
                    <td>
                        <!--<a asp-action="Edit" asp-route-id="@item.Key.AuthorID">Edit</a> |-->
                        <a asp-action="Details" asp-route-id="@item.Key.AuthorID">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>