CBIB/Controllers/UserManagementController.cs
using CBIB.Data;
using CBIB.Models;
using CBIB.Views.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace CBIB.Controllers
{
    //[Authorize(Roles="Global Administrator")]

    public class UserManagementController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly CBIBContext _CBIBContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserManagementController(
            ApplicationDbContext dbContext,
            CBIBContext CBIBContext,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _dbContext = dbContext;
            _CBIBContext = CBIBContext;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Author> authorList = null;
            var vm = new UserManagementIndexViewModel();
            vm.Users= _dbContext.Users.OrderBy(u => u.Email).Include(u => u.Roles).ToList();
            List<ApplicationUser> UserList = new List<ApplicationUser>();

            var user = await _userManager.GetUserAsync(User);
            long currentUserNode = (await _CBIBContext.Author.FindAsync(user.AuthorID)).NodeID;

            if (User.IsInRole("Global Administrator"))
            {
                vm.Users = _dbContext.Users.OrderBy(u => u.Email).Include(u => u.Roles).ToList();
            }

            else if (User.IsInRole("Node Administrator"))
            {
                authorList = _CBIBContext.Author.ToList();
                List<Author> list = new List<Author>();
                List<ApplicationUser> Users = new List<ApplicationUser>();

                foreach (Author a in authorList)
                {
                    if (a.NodeID == currentUserNode)
                    {
                        list.Add(a);
                    }
                }

                UserList = await _dbContext.Users.Include(r=>r.Roles).ToListAsync();

                foreach (ApplicationUser u in UserList.ToList())
                {
                    foreach (Author a in list)
                    {
                        if(u.AuthorID == a.AuthorID)
                        {
                            Users.Add(u);
                        }
                    }
                }
                vm.Users = Users;
            }
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> AddRole(string id)
        {
            var user = await GetUserById(id);
            var vm = new UserManagementAddRoleViewModel
            {
                Roles = GetAllRoles(),
                UserId = id,
                Email = user.Email
            };
            return View(vm);
        }
       
        [HttpPost]
        public async Task<IActionResult> AddRole(UserManagementAddRoleViewModel rvm)
        {
            var user = await GetUserById(rvm.UserId);
            if (ModelState.IsValid)
            {
                var result = await _userManager.AddToRoleAsync(user, rvm.NewRole);
            
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.Code, error.Description);
                }
            }
            rvm.Email = user.Email;
            rvm.Roles = GetAllRoles();
            return View(rvm);
        }

        private async Task<ApplicationUser> GetUserById(string id) =>
            await _userManager.FindByIdAsync(id);

        private SelectList GetAllRoles() => new SelectList(_roleManager.Roles.OrderBy(r => r.Name));
    }
}

CBIB/Views/UserManagement/AddNode.cshtml
@*﻿@model CBIB.Models.Node*@
@model CBIB.Views.ViewModels.UserManagementAddRoleViewModel

@{
    ViewData["Title"] = "Assign Node";
}

@{
    <h3>Add Node For @Model.Email</h3>
    <form asp-controller="UserManagement" asp-action="Index" method="post" asp-route-id="@Model.UserId" class="form-horizontal" role="form">
        <div class="form-group">
            <div class="row">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <select asp-for="ID"class="form-control"
                        asp-items="@(new SelectList(@ViewBag.ListOfNodes,"ID", "Name"))">
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    <input id="Submit1" type="submit" value="submit" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    @if (ViewBag.SelectedValue != null)
                    {
                        <text>Selected Country ID: </text> @ViewBag.SelectedValue;
                    }
                </div>
            </div>
        </div>
    </form>
}

CBIB/Views/UserManagement/AddRole.cshtml
 @model CBIB.Views.ViewModels.UserManagementAddRoleViewModel

<div class="container body-content">
    <h3>Add Role For @Model.Email</h3>
    <div asp-validation-summary="All"></div>
    <form asp-controller="UserManagement" asp-action="AddRole">
        <input asp-for="UserId" type="hidden" />
        <select asp-for="NewRole" asp-items="Model.Roles"></select>
        <input type="submit" value="Add Role"          
    </form>
</div>

CBIB/Views/UserManagement/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model CBIB.Views.ViewModels.UserManagementIndexViewModel
@inject UserManager<ApplicationUser> userManager

<div class="container body-content">
    <table class="table">
        <thead>
            <tr>
                <th>User ID</th>
                <th>Roles</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.Users)
            {
                <tr>
                    <td>@user.Email</td>
                    <td>@(string.Join(",", await userManager.GetRolesAsync(user)))</td>
                    <td><a asp-controller="UserManagement" asp-action="AddRole" asp-route-id="@user.Id">Add Role</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>